name: StrikePractice-Clan-Stats
version: ${project.version}
author: Simonsator
depends: [ Clans ]
depend: [ Clans ]
main: de.simonsator.partyandfriends.clan.stats.strikepractice.SPStatMain
description: Provides stats for clans for StrikePractice